#pragma once
#include <Winsock2.h>
#include <ws2bth.h>
#include <initguid.h>
#include <stdio.h>
#include <strsafe.h>

#include "DriverProxy.hpp"
#include "KeyboardProxy.hpp"
#include "ModeSwitcher.hpp"

// Autogenerated GUID: {223B9890-02FF-44B5-AD44-9CF50CB3BCE6}
DEFINE_GUID(bbGUID,
	0x223b9890, 0x2ff, 0x44b5, 0xad, 0x44, 0x9c, 0xf5, 0xc, 0xb3, 0xbc, 0xe6);

#define DEFAULT_DATA_LENGTH 512
#define LISTEN_BACKLOG_SIZE 1
#define CXN_SUCCESS 0
#define CXN_INSTANCE_STRING L"BBRemoteDesktopClient"

using namespace std;

class BluetoothReceiver {
private:
	DriverProxy *currentProxy;
	void cleanup();
public:
	BluetoothReceiver();
	~BluetoothReceiver();
	void receiveData();
	void handleData(char*,int);
};