#pragma once

#define SUCCESS 0
#define ERROR_NOT_AXIS_OR_BUTTON 1
#define ERROR_UNEVEN_BYTE_COUNT 2
#define ERROR_AXIS_DOES_NOT_EXIST 3
#define ERROR_BUTTON_DOES_NOT_EXIST 4
#define ERROR_BUTTON_VALUE_INVALID 5
#define ERROR_NOT_AXIS 6
#define ERROR_NOT_BUTTON 7