#pragma once

#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#include <initguid.h>

// {FB847750-0429-448A-9DA7-44EDB7E3EF04} // Autogenerated GUID for BBCam
DEFINE_GUID(BBCam_GUID,
	0xfb847750, 0x429, 0x448a, 0x9d, 0xa7, 0x44, 0xed, 0xb7, 0xe3, 0xef, 0x4);

#define DISPLAY_NAME L"BBCam"
#define CHAR_DISPLAY_NAME "BBCam"

#define BUFFER_FILE_NAME "C:\\Users\\Brendan\\Desktop\\out2.h264"
#define BUFFER_FILE_NAME_LEN 40

#endif